---
- name: reload systemd
  shell: systemctl daemon-reload

- name: restart kube-apiserver
  service: name=kube-apiserver.service state=restarted enabled=yes

- name: restart kube-controller-manager
  service: name=kube-controller-manager.service state=restarted enabled=yes

- name: restart kube-scheduler
  service: name=kube-scheduler.service state=restarted enabled=yes
