---
- name: install ELRepo
  shell: rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org && rpm -Uvh https://www.elrepo.org/elrepo-release-7.0-4.el7.elrepo.noarch.rpm

- name: install kernel
  yum: enablerepo=elrepo-kernel name=kernel-ml

- name: set boot kernel
  lineinfile: path=/etc/default/grub regexp="GRUB_DEFAULT=" line="GRUB_DEFAULT=0"

- name: cp /etc/default/grub
  shell: cp /etc/default/grub /etc/default/grub.bak

- name: add numa=off
  shell: sed -i 's/\(^GRUB_CMDLINE_LINUX=".*\)"$/\1 numa=off"/' /etc/default/grub

- name: grub2-mkconfig
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
