---
- name: add yum.conf
  lineinfile: regexp="exclude=kernel kernel-source kernel-smp" path=/etc/yum.conf backrefs=no line="exclude=kernel kernel-source kernel-smp"

- name: yum update
  shell: yum -y update

- name: install ELRepo
  shell: rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org && rpm -Uvh https://www.elrepo.org/elrepo-release-7.0-4.el7.elrepo.noarch.rpm
  ignore_errors: yes

- name: install kernel
  yum: enablerepo=elrepo-kernel name=kernel-ml

- name: cp /etc/default/grub
  shell: cp /etc/default/grub /etc/default/grub.bak

- name: set boot kernel 1
  copy: src=set_boot_kernel.sh dest=/tmp/ mode=755

- name: set boot kernel 2
  shell: /tmp/set_boot_kernel.sh

- name: set boot kernel 3
  file: path=/tmp/set_boot_kernel.sh state=absent

- name: grub2-mkconfig
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
