#!/usr/bin/env python
# pip install requests
# vim /etc/sysconfig/docker
#     other_args="-H unix:///var/run/docker.sock -H 127.0.0.1:4243"
#
import sys
import json
import requests

#if len(sys.argv) != 2:
#   print 'Usage: check_container_running container_name'
#   sys.exit(0)

#container = sys.argv[1]

containers = open('/data/zabbix/bin/container.txt','r')
results = []

for container in containers:
  container = container.replace('\n','')
  r = requests.get('http://127.0.0.1:4243/containers/' + container + '/json')
  if r.status_code == requests.codes.ok:
    res = r.json()
    running =  res['State']['Running']

    if running == False:
      results.append(container + ' CRITICAL, not running')
  else:
    results.append(container + ' WARNING, can not get container status')

if results:
   for result in results:
     print result

else:
  print 'Everything is OK'
