---
- name: mkdir /root/.docker
  file: path=/root/.docker state=directory mode=0700

- name: copy config.json
  copy: src=config.json dest=/root/.docker/ mode=0600

- name: add xg.cc to hosts registry
  lineinfile: path=/etc/hosts regexp='xg.cc' line='{{ REGISTRY }}    xg.cc' state=present

- name: add dockerCA.crt
  copy: src=devdockerCA.crt dest=/etc/pki/ca-trust/source/anchors/

- name: update-ca-trust
  shell: update-ca-trust extract
  notify:
  - restart docker

#- name: copy iptables.sh
#  template: src=iptables.sh.j2 dest=/opt/sh/iptables.sh mode=755
#  notify:
#  - start iptables

